In [36]:
import sys
sys.path.append("..")

from pathlib import Path
import pandas as pd
from turbofan.data import load_cmapss

In [37]:
RAW = Path("../data/raw")
path = Path(RAW / "test_FD001.txt")

In [38]:
test = load_cmapss(path)
test.sample(2)

       unit  cycle  setting_1  ...  sensor_19  sensor_20  sensor_21
10418    81     31    -0.0023  ...      100.0      38.97    23.3846
1051     10    156     0.0003  ...      100.0      38.92    23.3511

[2 rows x 26 columns]

In [39]:
test.shape

(13096, 26)

In [40]:
test_life = test.groupby('unit')["cycle"].max()

In [41]:
test_life.describe()

count    100.000000
mean     130.960000
std       53.593479
min       31.000000
25%       88.750000
50%      133.500000
75%      164.250000
max      303.000000
Name: cycle, dtype: float64

In [42]:
rul = pd.read_csv(RAW / "RUL_FD001.txt", sep=r"\s+", header=None, names=["rul"])

In [43]:
rul

    rul
0   112
1    98
2    69
3    82
4    91
..  ...
95  137
96   82
97   59
98  117
99   20

[100 rows x 1 columns]

In [44]:
print(rul.shape)
print(rul.head)

(100, 1)
<bound method NDFrame.head of     rul
0   112
1    98
2    69
3    82
4    91
..  ...
95  137
96   82
97   59
98  117
99   20

[100 rows x 1 columns]>

In [45]:
rul["unit"] = range(1, len(rul) + 1)
rul.head

<bound method NDFrame.head of     rul  unit
0   112     1
1    98     2
2    69     3
3    82     4
4    91     5
..  ...   ...
95  137    96
96   82    97
97   59    98
98  117    99
99   20   100

[100 rows x 2 columns]>

In [46]:
from turbofan.features import add_rolling_features

test_feat = add_rolling_features(test)
last_rows = test_feat.groupby("unit").tail(1)

In [47]:
print(last_rows.shape)
print(last_rows[["unit", "cycle", "sensor_11", "sensor_11_mean"]].head())

(100, 56)
     unit  cycle  sensor_11  sensor_11_mean
30      1     31      47.23          47.288
79      2     49      47.67          47.509
205     3    126      47.88          47.705
311     4    106      47.65          47.630
409     5     98      47.46          47.533

In [48]:
test_final = last_rows.merge(rul, on="unit")
print(test_final[["unit", "cycle", "rul"]].head())

   unit  cycle  rul
0     1     31  112
1     2     49   98
2     3    126   69
3     4    106   82
4     5     98   91

In [49]:
print(test_final.shape)

(100, 57)

In [50]:
test_final.head()

   unit  cycle  setting_1  ...  sensor_21_mean  sensor_21_std  rul
0     1     31    -0.0006  ...        23.36944       0.026390  112
1     2     49     0.0018  ...        23.29325       0.049705   98
2     3    126    -0.0016  ...        23.22671       0.039177   69
3     4    106     0.0012  ...        23.26245       0.054676   82
4     5     98    -0.0013  ...        23.25765       0.078644   91

[5 rows x 57 columns]

Loading the trained model back

In [51]:
import json
import joblib
from turbofan.data import load_test_rul
from turbofan.features import last_cycle_per_engine

ImportError: cannot import name 'load_test_rul' from 'turbofan.data' (c:\dev\predictive-maintenance-mlops\notebooks\..\turbofan\data.py)